#!/bin/bash	
#update vnstat for a given time

#vnstat-update [time to update]

if [  $# == 0 ]; then
	echo "Usage: $0 [interface] [time to update] "
else
	interface=$1
	zeit=$2
	fertig=1
	eta=0

	echo "Updating $interface DB every $zeit seconds"
	echo "Elapsed Time: " 

	while [ "$fertig" == 1 ] 
	do
		if [ "$eta" -lt 10 ]; then
			digits="\b"
		fi
		if [[ "$eta" -gt 9 || "$eta" -lt 100 ]]; then
			digits="\b\b"
		fi
		if [[ "$eta" -gt 99 || "$eta" -lt 1000 ]]; then
			digits="\b\b\b"
		fi
		 if [[ "$eta" -gt 999 || "$eta" -lt 10000 ]]; then
			digits="\b\b\b\b"
		fi
		 if [[ "$eta" -gt 9999 || "$eta" -lt 100000 ]]; then
			digits="\b\b\b\b\b"
		fi

		if [ "$eta" -lt 60 ]; then
			if [ "$eta" -lt 10 ]; then
				genau_zeit="0:00:0$eta"
			else
				genau_zeit="0:00:$eta"
			fi
		fi
#		if [ "$eta" -gt 59 ]; then
#			if [ "$eta" -gt 3599 ]; then
#				if [ "$eta" -lt  36000]; then
#					seconds_rest=$(( $eta % 3600))
#					hours=$(( $(($eta - $secons_rest))/ 3600 ))
#					min_rest=$(( $seconds_rest % 60 ))
#					min=$(( $(( $seconds_rest - $min_rest)) / 60))
#				fi
#			fi
#		fi
		
		echo -e -n "$eta$digits" 
		#echo -e -n "$eta$digits ($genau_zeit)" 
		sleep 1
		let "eta +=1"
		mod=$(($eta % $zeit))
		if [ $mod == 0 ]; then
			`vnstat -i $interface -u`
		fi
	done
fi

